CREATE TABLE "equipamientos" (
    "id" SERIAL PRIMARY KEY,
    "nombre" VARCHAR(255),
    "codigo" VARCHAR(100),
    "organizacion" INTEGER,
    "estado" INTEGER,
    "modelo" VARCHAR(255),
    "serie" VARCHAR(100),
    "fecha_asignacion" TIMESTAMP,
    "sucursal_id" INTEGER,
    "puesto_id" INTEGER,
    "propiedad" INTEGER,
    "tipo_equipo" INTEGER,
    "tipo" INTEGER,
    "uso_equipo" INTEGER,
    "uso_id" INTEGER,
    "detalles_uso" TEXT,
    "requerimientos" TEXT,
    "url_imagen" TEXT,
    "numero_economico" VARCHAR(100),
    "creado_id" INTEGER,
    "fecha_creacion" TIMESTAMP DEFAULT NOW(),
    "actualizado_id" INTEGER,
    "fecha_actualizacion" TIMESTAMP,
    "eliminado_id" INTEGER,
    "fecha_eliminacion" TIMESTAMP
);